// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_feed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedEvent = `-- name: CreateFeedEvent :one
INSERT INTO activity_feed (player_id, event_type, content, region_id)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, event_type, content, region_id, created_at
`

type CreateFeedEventParams struct {
	PlayerID  pgtype.UUID `json:"player_id"`
	EventType string      `json:"event_type"`
	Content   []byte      `json:"content"`
	RegionID  pgtype.UUID `json:"region_id"`
}

func (q *Queries) CreateFeedEvent(ctx context.Context, arg CreateFeedEventParams) (ActivityFeed, error) {
	row := q.db.QueryRow(ctx, createFeedEvent,
		arg.PlayerID,
		arg.EventType,
		arg.Content,
		arg.RegionID,
	)
	var i ActivityFeed
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EventType,
		&i.Content,
		&i.RegionID,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedByRegion = `-- name: GetFeedByRegion :many
SELECT
    af.id,
    af.player_id,
    af.event_type,
    af.content,
    af.region_id,
    af.created_at,
    u.name AS player_name
FROM activity_feed af
JOIN users u ON u.id = af.player_id
WHERE af.region_id = $1
ORDER BY af.created_at DESC
LIMIT $3 OFFSET $2
`

type GetFeedByRegionParams struct {
	RegionID   pgtype.UUID `json:"region_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type GetFeedByRegionRow struct {
	ID         pgtype.UUID        `json:"id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	EventType  string             `json:"event_type"`
	Content    []byte             `json:"content"`
	RegionID   pgtype.UUID        `json:"region_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	PlayerName pgtype.Text        `json:"player_name"`
}

func (q *Queries) GetFeedByRegion(ctx context.Context, arg GetFeedByRegionParams) ([]GetFeedByRegionRow, error) {
	rows, err := q.db.Query(ctx, getFeedByRegion, arg.RegionID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedByRegionRow{}
	for rows.Next() {
		var i GetFeedByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EventType,
			&i.Content,
			&i.RegionID,
			&i.CreatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerWinStreak = `-- name: GetPlayerWinStreak :many
SELECT
    CASE WHEN mr.winner_team = mp.team THEN TRUE ELSE FALSE END AS won
FROM match_players mp
JOIN matches m ON m.id = mp.match_id AND m.status = 'sealed'
JOIN match_results mr ON mr.match_id = mp.match_id
WHERE mp.player_id = $1
ORDER BY m.created_at DESC
LIMIT 10
`

func (q *Queries) GetPlayerWinStreak(ctx context.Context, playerID pgtype.UUID) ([]bool, error) {
	rows, err := q.db.Query(ctx, getPlayerWinStreak, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []bool{}
	for rows.Next() {
		var won bool
		if err := rows.Scan(&won); err != nil {
			return nil, err
		}
		items = append(items, won)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPlayerEventByType = `-- name: GetRecentPlayerEventByType :one
SELECT id, created_at
FROM activity_feed
WHERE player_id = $1
  AND event_type = $2
  AND created_at > NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentPlayerEventByTypeParams struct {
	PlayerID  pgtype.UUID `json:"player_id"`
	EventType string      `json:"event_type"`
}

type GetRecentPlayerEventByTypeRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentPlayerEventByType(ctx context.Context, arg GetRecentPlayerEventByTypeParams) (GetRecentPlayerEventByTypeRow, error) {
	row := q.db.QueryRow(ctx, getRecentPlayerEventByType, arg.PlayerID, arg.EventType)
	var i GetRecentPlayerEventByTypeRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
