// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banPlayer = `-- name: BanPlayer :exec
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type BanPlayerParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) BanPlayer(ctx context.Context, arg BanPlayerParams) error {
	_, err := q.db.Exec(ctx, banPlayer, arg.ID, arg.Status)
	return err
}

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*)::BIGINT FROM admin_audit_log
WHERE ($1::UUID IS NULL OR admin_id = $1)
`

func (q *Queries) CountAuditLog(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createModerator = `-- name: CreateModerator :one
INSERT INTO users (email, password_hash, name, last_name, role, status, region_id, trust_score)
VALUES ($1, $2, $3, $4, 'moderator', 'active', $5, 80)
RETURNING id, email, name, last_name, role, status, region_id, created_at
`

type CreateModeratorParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	LastName     pgtype.Text `json:"last_name"`
	RegionID     pgtype.UUID `json:"region_id"`
}

type CreateModeratorRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	LastName  pgtype.Text        `json:"last_name"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	RegionID  pgtype.UUID        `json:"region_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateModerator(ctx context.Context, arg CreateModeratorParams) (CreateModeratorRow, error) {
	row := q.db.QueryRow(ctx, createModerator,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.LastName,
		arg.RegionID,
	)
	var i CreateModeratorRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.RegionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteModerator = `-- name: DeleteModerator :exec
UPDATE users
SET role = 'player', region_id = NULL, updated_at = NOW()
WHERE id = $1 AND role = 'moderator'
`

func (q *Queries) DeleteModerator(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteModerator, id)
	return err
}

const getKPIs = `-- name: GetKPIs :one
SELECT
    (SELECT COUNT(*) FROM users WHERE role = 'player')::BIGINT                                        AS total_players,
    (SELECT COUNT(*) FROM users WHERE role = 'player' AND status = 'active')::BIGINT                  AS active_players,
    (SELECT COUNT(*) FROM users WHERE status IN ('banned_soft', 'banned_hard'))::BIGINT               AS banned_players,
    (SELECT COUNT(*) FROM matches)::BIGINT                                                            AS total_matches,
    (SELECT COUNT(*) FROM matches WHERE status = 'sealed')::BIGINT                                    AS completed_matches,
    (SELECT COUNT(*) FROM disputes WHERE status = 'pending')::BIGINT                                  AS pending_disputes,
    COALESCE((SELECT AVG(elo) FROM users WHERE role = 'player' AND status = 'active'), 0)::FLOAT8     AS avg_elo,
    (SELECT COUNT(*) FROM users WHERE role = 'moderator')::BIGINT                                     AS total_moderators
`

type GetKPIsRow struct {
	TotalPlayers     int64   `json:"total_players"`
	ActivePlayers    int64   `json:"active_players"`
	BannedPlayers    int64   `json:"banned_players"`
	TotalMatches     int64   `json:"total_matches"`
	CompletedMatches int64   `json:"completed_matches"`
	PendingDisputes  int64   `json:"pending_disputes"`
	AvgElo           float64 `json:"avg_elo"`
	TotalModerators  int64   `json:"total_moderators"`
}

func (q *Queries) GetKPIs(ctx context.Context) (GetKPIsRow, error) {
	row := q.db.QueryRow(ctx, getKPIs)
	var i GetKPIsRow
	err := row.Scan(
		&i.TotalPlayers,
		&i.ActivePlayers,
		&i.BannedPlayers,
		&i.TotalMatches,
		&i.CompletedMatches,
		&i.PendingDisputes,
		&i.AvgElo,
		&i.TotalModerators,
	)
	return i, err
}

const getUserELO = `-- name: GetUserELO :one
SELECT elo FROM users WHERE id = $1
`

func (q *Queries) GetUserELO(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserELO, id)
	var elo int32
	err := row.Scan(&elo)
	return elo, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_log (admin_id, action, target_user_id, details)
VALUES ($1, $2, $3, $4)
`

type InsertAuditLogParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	Action       string      `json:"action"`
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Details      []byte      `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetUserID,
		arg.Details,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, admin_id, action, target_user_id, details, created_at
FROM admin_audit_log
WHERE ($1::UUID IS NULL OR admin_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetUserID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerators = `-- name: ListModerators :many
SELECT id, email, name, last_name, role, status, region_id, created_at
FROM users
WHERE role = 'moderator'
ORDER BY created_at ASC
`

type ListModeratorsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	LastName  pgtype.Text        `json:"last_name"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	RegionID  pgtype.UUID        `json:"region_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListModerators(ctx context.Context) ([]ListModeratorsRow, error) {
	rows, err := q.db.Query(ctx, listModerators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModeratorsRow{}
	for rows.Next() {
		var i ListModeratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.LastName,
			&i.Role,
			&i.Status,
			&i.RegionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanPlayer = `-- name: UnbanPlayer :exec
UPDATE users
SET status = 'active', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UnbanPlayer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unbanPlayer, id)
	return err
}

const updateModerator = `-- name: UpdateModerator :one
UPDATE users
SET region_id = $2, updated_at = NOW()
WHERE id = $1 AND role = 'moderator'
RETURNING id, email, name, last_name, role, status, region_id, created_at
`

type UpdateModeratorParams struct {
	ID       pgtype.UUID `json:"id"`
	RegionID pgtype.UUID `json:"region_id"`
}

type UpdateModeratorRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	LastName  pgtype.Text        `json:"last_name"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	RegionID  pgtype.UUID        `json:"region_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateModerator(ctx context.Context, arg UpdateModeratorParams) (UpdateModeratorRow, error) {
	row := q.db.QueryRow(ctx, updateModerator, arg.ID, arg.RegionID)
	var i UpdateModeratorRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.RegionID,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserELO = `-- name: UpdateUserELO :exec
UPDATE users SET elo = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserELOParams struct {
	ID  pgtype.UUID `json:"id"`
	Elo int32       `json:"elo"`
}

func (q *Queries) UpdateUserELO(ctx context.Context, arg UpdateUserELOParams) error {
	_, err := q.db.Exec(ctx, updateUserELO, arg.ID, arg.Elo)
	return err
}
