// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conduct_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllReports = `-- name: CountAllReports :one
SELECT COUNT(*)
FROM conduct_reports cr
WHERE (CASE WHEN $1::varchar = '' THEN TRUE ELSE cr.status = $1::varchar END)
`

func (q *Queries) CountAllReports(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllReports, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReportsByRegion = `-- name: CountReportsByRegion :one
SELECT COUNT(*)
FROM conduct_reports cr
JOIN matches m ON m.id = cr.match_id
WHERE m.region_id = $1
  AND (CASE WHEN $2::varchar = '' THEN TRUE ELSE cr.status = $2::varchar END)
`

type CountReportsByRegionParams struct {
	RegionID pgtype.UUID `json:"region_id"`
	Column2  string      `json:"column_2"`
}

func (q *Queries) CountReportsByRegion(ctx context.Context, arg CountReportsByRegionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByRegion, arg.RegionID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO conduct_reports (reporter_id, reported_id, match_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, reporter_id, reported_id, match_id, reason, status, moderator_id, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	ReportedID pgtype.UUID `json:"reported_id"`
	MatchID    pgtype.UUID `json:"match_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (ConductReport, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.ReportedID,
		arg.MatchID,
		arg.Reason,
	)
	var i ConductReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedID,
		&i.MatchID,
		&i.Reason,
		&i.Status,
		&i.ModeratorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllReports = `-- name: GetAllReports :many
SELECT cr.id, cr.reporter_id, cr.reported_id, cr.match_id, cr.reason, cr.status, cr.moderator_id, cr.created_at, cr.updated_at
FROM conduct_reports cr
WHERE (CASE WHEN $1::varchar = '' THEN TRUE ELSE cr.status = $1::varchar END)
ORDER BY cr.created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllReportsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetAllReports(ctx context.Context, arg GetAllReportsParams) ([]ConductReport, error) {
	rows, err := q.db.Query(ctx, getAllReports, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConductReport{}
	for rows.Next() {
		var i ConductReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedID,
			&i.MatchID,
			&i.Reason,
			&i.Status,
			&i.ModeratorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByPlayer = `-- name: GetReportsByPlayer :many
SELECT id, reporter_id, reported_id, match_id, reason, status, moderator_id, created_at, updated_at
FROM conduct_reports
WHERE reported_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetReportsByPlayerParams struct {
	ReportedID pgtype.UUID `json:"reported_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) GetReportsByPlayer(ctx context.Context, arg GetReportsByPlayerParams) ([]ConductReport, error) {
	rows, err := q.db.Query(ctx, getReportsByPlayer, arg.ReportedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConductReport{}
	for rows.Next() {
		var i ConductReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedID,
			&i.MatchID,
			&i.Reason,
			&i.Status,
			&i.ModeratorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByRegion = `-- name: GetReportsByRegion :many
SELECT cr.id, cr.reporter_id, cr.reported_id, cr.match_id, cr.reason, cr.status, cr.moderator_id, cr.created_at, cr.updated_at
FROM conduct_reports cr
JOIN matches m ON m.id = cr.match_id
WHERE m.region_id = $1
  AND (CASE WHEN $2::varchar = '' THEN TRUE ELSE cr.status = $2::varchar END)
ORDER BY cr.created_at DESC
LIMIT $3 OFFSET $4
`

type GetReportsByRegionParams struct {
	RegionID pgtype.UUID `json:"region_id"`
	Column2  string      `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetReportsByRegion(ctx context.Context, arg GetReportsByRegionParams) ([]ConductReport, error) {
	rows, err := q.db.Query(ctx, getReportsByRegion,
		arg.RegionID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConductReport{}
	for rows.Next() {
		var i ConductReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReportedID,
			&i.MatchID,
			&i.Reason,
			&i.Status,
			&i.ModeratorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMatchCompleted = `-- name: IsMatchCompleted :one
SELECT EXISTS(
    SELECT 1 FROM matches WHERE id = $1 AND status = 'sealed'
)
`

func (q *Queries) IsMatchCompleted(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isMatchCompleted, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMatchParticipant = `-- name: IsMatchParticipant :one
SELECT EXISTS(
    SELECT 1 FROM match_players WHERE match_id = $1 AND player_id = $2
)
`

type IsMatchParticipantParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) IsMatchParticipant(ctx context.Context, arg IsMatchParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMatchParticipant, arg.MatchID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
