// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE player_id = $1 AND token = $2
`

type DeleteDeviceTokenParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Token    string      `json:"token"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.PlayerID, arg.Token)
	return err
}

const getDeviceTokensByPlayer = `-- name: GetDeviceTokensByPlayer :many
SELECT token FROM device_tokens
WHERE player_id = $1
ORDER BY last_used_at DESC
`

func (q *Queries) GetDeviceTokensByPlayer(ctx context.Context, playerID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (player_id, token, platform, last_used_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (player_id, token)
DO UPDATE SET platform = EXCLUDED.platform, last_used_at = NOW()
`

type UpsertDeviceTokenParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Token    string      `json:"token"`
	Platform string      `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.PlayerID, arg.Token, arg.Platform)
	return err
}
