// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disputes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO disputes (match_id, raised_by, reason)
VALUES ($1, $2, $3)
RETURNING id, match_id, raised_by, reason, status, resolved_by, resolution_result, penalized_player_id, resolved_at, created_at
`

type CreateDisputeParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	RaisedBy pgtype.UUID `json:"raised_by"`
	Reason   string      `json:"reason"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, createDispute, arg.MatchID, arg.RaisedBy, arg.Reason)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionResult,
		&i.PenalizedPlayerID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDisputeByID = `-- name: GetDisputeByID :one
SELECT id, match_id, raised_by, reason, status, resolved_by, resolution_result, penalized_player_id, resolved_at, created_at
FROM disputes
WHERE id = $1
`

func (q *Queries) GetDisputeByID(ctx context.Context, id pgtype.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDisputeByID, id)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionResult,
		&i.PenalizedPlayerID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDisputeByMatch = `-- name: GetDisputeByMatch :one
SELECT id, match_id, raised_by, reason, status, resolved_by, resolution_result, penalized_player_id, resolved_at, created_at
FROM disputes
WHERE match_id = $1
`

func (q *Queries) GetDisputeByMatch(ctx context.Context, matchID pgtype.UUID) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDisputeByMatch, matchID)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionResult,
		&i.PenalizedPlayerID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDisputesByStatus = `-- name: GetDisputesByStatus :many
SELECT id, match_id, raised_by, reason, status, resolved_by, resolution_result, penalized_player_id, resolved_at, created_at
FROM disputes
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) GetDisputesByStatus(ctx context.Context, status string) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, getDisputesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dispute{}
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.RaisedBy,
			&i.Reason,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolutionResult,
			&i.PenalizedPlayerID,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDispute = `-- name: ResolveDispute :exec
UPDATE disputes
SET
    resolved_by = $2,
    resolution_result = $3,
    penalized_player_id = $4,
    resolved_at = NOW(),
    status = 'resolved'
WHERE id = $1
`

type ResolveDisputeParams struct {
	ID                pgtype.UUID `json:"id"`
	ResolvedBy        pgtype.UUID `json:"resolved_by"`
	ResolutionResult  []byte      `json:"resolution_result"`
	PenalizedPlayerID pgtype.UUID `json:"penalized_player_id"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) error {
	_, err := q.db.Exec(ctx, resolveDispute,
		arg.ID,
		arg.ResolvedBy,
		arg.ResolutionResult,
		arg.PenalizedPlayerID,
	)
	return err
}
