// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elo_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getELOHistory = `-- name: GetELOHistory :many
SELECT id, player_id, match_id, elo_before, elo_after, delta, k_factor, type, created_at FROM elo_history WHERE player_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetELOHistoryParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetELOHistory(ctx context.Context, arg GetELOHistoryParams) ([]EloHistory, error) {
	rows, err := q.db.Query(ctx, getELOHistory, arg.PlayerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloHistory{}
	for rows.Next() {
		var i EloHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchID,
			&i.EloBefore,
			&i.EloAfter,
			&i.Delta,
			&i.KFactor,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getELOHistoryByMatch = `-- name: GetELOHistoryByMatch :many
SELECT id, player_id, match_id, elo_before, elo_after, delta, k_factor, type, created_at FROM elo_history WHERE match_id = $1
`

func (q *Queries) GetELOHistoryByMatch(ctx context.Context, matchID pgtype.UUID) ([]EloHistory, error) {
	rows, err := q.db.Query(ctx, getELOHistoryByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EloHistory{}
	for rows.Next() {
		var i EloHistory
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchID,
			&i.EloBefore,
			&i.EloAfter,
			&i.Delta,
			&i.KFactor,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertELOHistory = `-- name: InsertELOHistory :one
INSERT INTO elo_history (player_id, match_id, elo_before, elo_after, delta, k_factor, type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, player_id, match_id, elo_before, elo_after, delta, k_factor, type, created_at
`

type InsertELOHistoryParams struct {
	PlayerID  pgtype.UUID `json:"player_id"`
	MatchID   pgtype.UUID `json:"match_id"`
	EloBefore int32       `json:"elo_before"`
	EloAfter  int32       `json:"elo_after"`
	Delta     int32       `json:"delta"`
	KFactor   int32       `json:"k_factor"`
	Type      string      `json:"type"`
}

func (q *Queries) InsertELOHistory(ctx context.Context, arg InsertELOHistoryParams) (EloHistory, error) {
	row := q.db.QueryRow(ctx, insertELOHistory,
		arg.PlayerID,
		arg.MatchID,
		arg.EloBefore,
		arg.EloAfter,
		arg.Delta,
		arg.KFactor,
		arg.Type,
	)
	var i EloHistory
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchID,
		&i.EloBefore,
		&i.EloAfter,
		&i.Delta,
		&i.KFactor,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
