// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elo_history_extended.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getELOHistoryWithOpponents = `-- name: GetELOHistoryWithOpponents :many
SELECT
    eh.id,
    eh.match_id,
    eh.elo_before,
    eh.elo_after,
    (eh.elo_after - eh.elo_before) AS delta,
    eh.created_at,
    u.id   AS opponent_id,
    u.name AS opponent_name
FROM elo_history eh
JOIN match_players mp ON mp.match_id = eh.match_id AND mp.player_id != $1
JOIN users u ON u.id = mp.player_id
WHERE eh.player_id = $1
  AND ($2::timestamptz IS NULL OR eh.created_at < $2)
ORDER BY eh.created_at DESC, eh.id DESC
LIMIT $3
`

type GetELOHistoryWithOpponentsParams struct {
	PlayerID pgtype.UUID        `json:"player_id"`
	Column2  pgtype.Timestamptz `json:"column_2"`
	Limit    int32              `json:"limit"`
}

type GetELOHistoryWithOpponentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	EloBefore    int32              `json:"elo_before"`
	EloAfter     int32              `json:"elo_after"`
	Delta        int32              `json:"delta"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	OpponentID   pgtype.UUID        `json:"opponent_id"`
	OpponentName pgtype.Text        `json:"opponent_name"`
}

func (q *Queries) GetELOHistoryWithOpponents(ctx context.Context, arg GetELOHistoryWithOpponentsParams) ([]GetELOHistoryWithOpponentsRow, error) {
	rows, err := q.db.Query(ctx, getELOHistoryWithOpponents, arg.PlayerID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetELOHistoryWithOpponentsRow{}
	for rows.Next() {
		var i GetELOHistoryWithOpponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.EloBefore,
			&i.EloAfter,
			&i.Delta,
			&i.CreatedAt,
			&i.OpponentID,
			&i.OpponentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
