// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flares.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFlareRespondent = `-- name: AddFlareRespondent :exec
INSERT INTO flare_respondents (flare_id, player_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFlareRespondentParams struct {
	FlareID  pgtype.UUID `json:"flare_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) AddFlareRespondent(ctx context.Context, arg AddFlareRespondentParams) error {
	_, err := q.db.Exec(ctx, addFlareRespondent, arg.FlareID, arg.PlayerID)
	return err
}

const cancelFlare = `-- name: CancelFlare :one
UPDATE matchmaking_flares
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND player_id = $2 AND status = 'active'
RETURNING id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id
`

type CancelFlareParams struct {
	ID       pgtype.UUID `json:"id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) CancelFlare(ctx context.Context, arg CancelFlareParams) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, cancelFlare, arg.ID, arg.PlayerID)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}

const countFlareRespondents = `-- name: CountFlareRespondents :one
SELECT COUNT(*)::INT FROM flare_respondents WHERE flare_id = $1
`

func (q *Queries) CountFlareRespondents(ctx context.Context, flareID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFlareRespondents, flareID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createFlare = `-- name: CreateFlare :one
INSERT INTO matchmaking_flares (player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, match_type, venue_id)
VALUES ($1, ST_MakePoint($2, $3)::geography, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id
`

type CreateFlareParams struct {
	PlayerID    pgtype.UUID        `json:"player_id"`
	Lng         interface{}        `json:"lng"`
	Lat         interface{}        `json:"lat"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	EloMin      int32              `json:"elo_min"`
	EloMax      int32              `json:"elo_max"`
	MinPlayers  int32              `json:"min_players"`
	MaxPlayers  int32              `json:"max_players"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
}

func (q *Queries) CreateFlare(ctx context.Context, arg CreateFlareParams) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, createFlare,
		arg.PlayerID,
		arg.Lng,
		arg.Lat,
		arg.ScheduledAt,
		arg.EloMin,
		arg.EloMax,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.MatchType,
		arg.VenueID,
	)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}

const expireOldFlares = `-- name: ExpireOldFlares :execrows
UPDATE matchmaking_flares
SET status = 'expired', updated_at = NOW()
WHERE status = 'active' AND expires_at < NOW()
`

func (q *Queries) ExpireOldFlares(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldFlares)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveFlareByPlayer = `-- name: GetActiveFlareByPlayer :one
SELECT id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id FROM matchmaking_flares
WHERE player_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveFlareByPlayer(ctx context.Context, playerID pgtype.UUID) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, getActiveFlareByPlayer, playerID)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}

const getActiveFlares = `-- name: GetActiveFlares :many
SELECT
    f.id,
    f.player_id,
    f.scheduled_at,
    f.elo_min,
    f.elo_max,
    f.min_players,
    f.max_players,
    f.match_type,
    f.venue_id,
    f.status,
    f.match_id,
    f.expires_at,
    f.created_at,
    f.updated_at,
    p.name AS creator_name,
    ST_Y(f.location::geometry) AS lat,
    ST_X(f.location::geometry) AS lng,
    ST_Distance(f.location, ST_MakePoint($1, $2)::geography) AS distance_meters,
    (SELECT COUNT(*)::INT FROM flare_respondents fr WHERE fr.flare_id = f.id) AS respondent_count
FROM matchmaking_flares f
JOIN users p ON p.id = f.player_id
JOIN users viewer ON viewer.id = $3
WHERE f.status = 'active'
  AND f.expires_at > NOW()
  AND ST_DWithin(f.location, ST_MakePoint($1, $2)::geography, $4)
  AND f.elo_min <= viewer.elo
  AND f.elo_max >= viewer.elo
  AND p.trust_score >= $5
  AND (
      f.created_at < $6
      OR (f.created_at = $6 AND f.id < $7::uuid)
  )
ORDER BY f.created_at DESC, f.id DESC
LIMIT $8
`

type GetActiveFlaresParams struct {
	Lng             interface{}        `json:"lng"`
	Lat             interface{}        `json:"lat"`
	ViewerPlayerID  pgtype.UUID        `json:"viewer_player_id"`
	RadiusMeters    interface{}        `json:"radius_meters"`
	MinTrustScore   int32              `json:"min_trust_score"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type GetActiveFlaresRow struct {
	ID              pgtype.UUID        `json:"id"`
	PlayerID        pgtype.UUID        `json:"player_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	EloMin          int32              `json:"elo_min"`
	EloMax          int32              `json:"elo_max"`
	MinPlayers      int32              `json:"min_players"`
	MaxPlayers      int32              `json:"max_players"`
	MatchType       string             `json:"match_type"`
	VenueID         pgtype.UUID        `json:"venue_id"`
	Status          string             `json:"status"`
	MatchID         pgtype.UUID        `json:"match_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatorName     pgtype.Text        `json:"creator_name"`
	Lat             interface{}        `json:"lat"`
	Lng             interface{}        `json:"lng"`
	DistanceMeters  interface{}        `json:"distance_meters"`
	RespondentCount int32              `json:"respondent_count"`
}

func (q *Queries) GetActiveFlares(ctx context.Context, arg GetActiveFlaresParams) ([]GetActiveFlaresRow, error) {
	rows, err := q.db.Query(ctx, getActiveFlares,
		arg.Lng,
		arg.Lat,
		arg.ViewerPlayerID,
		arg.RadiusMeters,
		arg.MinTrustScore,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveFlaresRow{}
	for rows.Next() {
		var i GetActiveFlaresRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ScheduledAt,
			&i.EloMin,
			&i.EloMax,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.MatchType,
			&i.VenueID,
			&i.Status,
			&i.MatchID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
			&i.RespondentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveFlaresByMatchType = `-- name: GetActiveFlaresByMatchType :many
SELECT
    f.id,
    f.player_id,
    f.scheduled_at,
    f.elo_min,
    f.elo_max,
    f.min_players,
    f.max_players,
    f.match_type,
    f.venue_id,
    f.status,
    f.match_id,
    f.expires_at,
    f.created_at,
    f.updated_at,
    p.name AS creator_name,
    ST_Y(f.location::geometry) AS lat,
    ST_X(f.location::geometry) AS lng,
    ST_Distance(f.location, ST_MakePoint($1, $2)::geography) AS distance_meters,
    (SELECT COUNT(*)::INT FROM flare_respondents fr WHERE fr.flare_id = f.id) AS respondent_count
FROM matchmaking_flares f
JOIN users p ON p.id = f.player_id
JOIN users viewer ON viewer.id = $3
WHERE f.status = 'active'
  AND f.expires_at > NOW()
  AND f.match_type = $4
  AND ST_DWithin(f.location, ST_MakePoint($1, $2)::geography, $5)
  AND f.elo_min <= viewer.elo
  AND f.elo_max >= viewer.elo
  AND p.trust_score >= $6
  AND (
      f.created_at < $7
      OR (f.created_at = $7 AND f.id < $8::uuid)
  )
ORDER BY f.created_at DESC, f.id DESC
LIMIT $9
`

type GetActiveFlaresByMatchTypeParams struct {
	Lng             interface{}        `json:"lng"`
	Lat             interface{}        `json:"lat"`
	ViewerPlayerID  pgtype.UUID        `json:"viewer_player_id"`
	MatchType       string             `json:"match_type"`
	RadiusMeters    interface{}        `json:"radius_meters"`
	MinTrustScore   int32              `json:"min_trust_score"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type GetActiveFlaresByMatchTypeRow struct {
	ID              pgtype.UUID        `json:"id"`
	PlayerID        pgtype.UUID        `json:"player_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	EloMin          int32              `json:"elo_min"`
	EloMax          int32              `json:"elo_max"`
	MinPlayers      int32              `json:"min_players"`
	MaxPlayers      int32              `json:"max_players"`
	MatchType       string             `json:"match_type"`
	VenueID         pgtype.UUID        `json:"venue_id"`
	Status          string             `json:"status"`
	MatchID         pgtype.UUID        `json:"match_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatorName     pgtype.Text        `json:"creator_name"`
	Lat             interface{}        `json:"lat"`
	Lng             interface{}        `json:"lng"`
	DistanceMeters  interface{}        `json:"distance_meters"`
	RespondentCount int32              `json:"respondent_count"`
}

func (q *Queries) GetActiveFlaresByMatchType(ctx context.Context, arg GetActiveFlaresByMatchTypeParams) ([]GetActiveFlaresByMatchTypeRow, error) {
	rows, err := q.db.Query(ctx, getActiveFlaresByMatchType,
		arg.Lng,
		arg.Lat,
		arg.ViewerPlayerID,
		arg.MatchType,
		arg.RadiusMeters,
		arg.MinTrustScore,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveFlaresByMatchTypeRow{}
	for rows.Next() {
		var i GetActiveFlaresByMatchTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ScheduledAt,
			&i.EloMin,
			&i.EloMax,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.MatchType,
			&i.VenueID,
			&i.Status,
			&i.MatchID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
			&i.RespondentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlareByID = `-- name: GetFlareByID :one
SELECT id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id FROM matchmaking_flares WHERE id = $1
`

func (q *Queries) GetFlareByID(ctx context.Context, id pgtype.UUID) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, getFlareByID, id)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}

const getFlareByIDForUpdate = `-- name: GetFlareByIDForUpdate :one
SELECT id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id FROM matchmaking_flares WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetFlareByIDForUpdate(ctx context.Context, id pgtype.UUID) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, getFlareByIDForUpdate, id)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}

const getFlareRespondents = `-- name: GetFlareRespondents :many
SELECT player_id FROM flare_respondents WHERE flare_id = $1
`

func (q *Queries) GetFlareRespondents(ctx context.Context, flareID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getFlareRespondents, flareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var player_id pgtype.UUID
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlareStatus = `-- name: UpdateFlareStatus :one
UPDATE matchmaking_flares
SET status = $1, match_id = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, player_id, location, scheduled_at, elo_min, elo_max, min_players, max_players, status, match_id, expires_at, created_at, updated_at, match_type, venue_id
`

type UpdateFlareStatusParams struct {
	Status  string      `json:"status"`
	MatchID pgtype.UUID `json:"match_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFlareStatus(ctx context.Context, arg UpdateFlareStatusParams) (MatchmakingFlare, error) {
	row := q.db.QueryRow(ctx, updateFlareStatus, arg.Status, arg.MatchID, arg.ID)
	var i MatchmakingFlare
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Location,
		&i.ScheduledAt,
		&i.EloMin,
		&i.EloMax,
		&i.MinPlayers,
		&i.MaxPlayers,
		&i.Status,
		&i.MatchID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchType,
		&i.VenueID,
	)
	return i, err
}
