// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchPlayers = `-- name: GetMatchPlayers :many
SELECT match_id, player_id, team
FROM match_players
WHERE match_id = $1
`

func (q *Queries) GetMatchPlayers(ctx context.Context, matchID pgtype.UUID) ([]MatchPlayer, error) {
	rows, err := q.db.Query(ctx, getMatchPlayers, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPlayer{}
	for rows.Next() {
		var i MatchPlayer
		if err := rows.Scan(&i.MatchID, &i.PlayerID, &i.Team); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchPlayersByTeam = `-- name: GetMatchPlayersByTeam :many
SELECT match_id, player_id, team
FROM match_players
WHERE match_id = $1 AND team = $2
`

type GetMatchPlayersByTeamParams struct {
	MatchID pgtype.UUID `json:"match_id"`
	Team    string      `json:"team"`
}

func (q *Queries) GetMatchPlayersByTeam(ctx context.Context, arg GetMatchPlayersByTeamParams) ([]MatchPlayer, error) {
	rows, err := q.db.Query(ctx, getMatchPlayersByTeam, arg.MatchID, arg.Team)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPlayer{}
	for rows.Next() {
		var i MatchPlayer
		if err := rows.Scan(&i.MatchID, &i.PlayerID, &i.Team); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatchPlayer = `-- name: InsertMatchPlayer :exec
INSERT INTO match_players (match_id, player_id, team)
VALUES ($1, $2, $3)
`

type InsertMatchPlayerParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
	Team     string      `json:"team"`
}

func (q *Queries) InsertMatchPlayer(ctx context.Context, arg InsertMatchPlayerParams) error {
	_, err := q.db.Exec(ctx, insertMatchPlayer, arg.MatchID, arg.PlayerID, arg.Team)
	return err
}
