// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (status, scheduled_at, location, captain_a_id, captain_b_id, avg_elo, match_type, venue_id)
VALUES (
    'pending_result',
    $1,
    ST_MakePoint($3, $2)::geography,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, status, scheduled_at, captain_a_id, captain_b_id, avg_elo, match_type, venue_id, sealed_by, created_at, updated_at
`

type CreateMatchParams struct {
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	StMakepoint   interface{}        `json:"st_makepoint"`
	StMakepoint_2 interface{}        `json:"st_makepoint_2"`
	CaptainAID    pgtype.UUID        `json:"captain_a_id"`
	CaptainBID    pgtype.UUID        `json:"captain_b_id"`
	AvgElo        pgtype.Int4        `json:"avg_elo"`
	MatchType     string             `json:"match_type"`
	VenueID       pgtype.UUID        `json:"venue_id"`
}

type CreateMatchRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.ScheduledAt,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.CaptainAID,
		arg.CaptainBID,
		arg.AvgElo,
		arg.MatchType,
		arg.VenueID,
	)
	var i CreateMatchRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ScheduledAt,
		&i.CaptainAID,
		&i.CaptainBID,
		&i.AvgElo,
		&i.MatchType,
		&i.VenueID,
		&i.SealedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMatchesByPlayer = `-- name: GetActiveMatchesByPlayer :many
SELECT m.id, m.status, m.scheduled_at, m.captain_a_id, m.captain_b_id, m.avg_elo, m.match_type, m.venue_id, m.sealed_by, m.created_at, m.updated_at
FROM matches m
JOIN match_players mp ON mp.match_id = m.id
WHERE mp.player_id = $1 AND m.status != 'sealed' AND m.status != 'cancelled'
ORDER BY m.scheduled_at ASC
`

type GetActiveMatchesByPlayerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveMatchesByPlayer(ctx context.Context, playerID pgtype.UUID) ([]GetActiveMatchesByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getActiveMatchesByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMatchesByPlayerRow{}
	for rows.Next() {
		var i GetActiveMatchesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ScheduledAt,
			&i.CaptainAID,
			&i.CaptainBID,
			&i.AvgElo,
			&i.MatchType,
			&i.VenueID,
			&i.SealedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, status, scheduled_at, captain_a_id, captain_b_id, avg_elo, match_type, venue_id, sealed_by, created_at, updated_at
FROM matches
WHERE id = $1
`

type GetMatchByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (GetMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ScheduledAt,
		&i.CaptainAID,
		&i.CaptainBID,
		&i.AvgElo,
		&i.MatchType,
		&i.VenueID,
		&i.SealedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchByIDForUpdate = `-- name: GetMatchByIDForUpdate :one
SELECT id, status, scheduled_at, captain_a_id, captain_b_id, avg_elo, match_type, venue_id, sealed_by, created_at, updated_at
FROM matches
WHERE id = $1
FOR UPDATE
`

type GetMatchByIDForUpdateRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetMatchByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMatchByIDForUpdate, id)
	var i GetMatchByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ScheduledAt,
		&i.CaptainAID,
		&i.CaptainBID,
		&i.AvgElo,
		&i.MatchType,
		&i.VenueID,
		&i.SealedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchesAwaitingConfirmation = `-- name: GetMatchesAwaitingConfirmation :many
SELECT m.id, m.status, m.scheduled_at, m.captain_a_id, m.captain_b_id, m.avg_elo, m.match_type, m.venue_id, m.sealed_by, m.created_at, m.updated_at
FROM matches m
JOIN match_results mr ON mr.match_id = m.id
WHERE m.status = 'awaiting_confirmation'
AND mr.submitted_at < NOW() - INTERVAL '6 hours'
`

type GetMatchesAwaitingConfirmationRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchesAwaitingConfirmation(ctx context.Context) ([]GetMatchesAwaitingConfirmationRow, error) {
	rows, err := q.db.Query(ctx, getMatchesAwaitingConfirmation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchesAwaitingConfirmationRow{}
	for rows.Next() {
		var i GetMatchesAwaitingConfirmationRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ScheduledAt,
			&i.CaptainAID,
			&i.CaptainBID,
			&i.AvgElo,
			&i.MatchType,
			&i.VenueID,
			&i.SealedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchesByPlayer = `-- name: GetMatchesByPlayer :many
SELECT m.id, m.status, m.scheduled_at, m.captain_a_id, m.captain_b_id, m.avg_elo, m.match_type, m.venue_id, m.sealed_by, m.created_at, m.updated_at
FROM matches m
JOIN match_players mp ON mp.match_id = m.id
WHERE mp.player_id = $1 AND m.status = 'sealed'
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMatchesByPlayerParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetMatchesByPlayerRow struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchesByPlayer(ctx context.Context, arg GetMatchesByPlayerParams) ([]GetMatchesByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getMatchesByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchesByPlayerRow{}
	for rows.Next() {
		var i GetMatchesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ScheduledAt,
			&i.CaptainAID,
			&i.CaptainBID,
			&i.AvgElo,
			&i.MatchType,
			&i.VenueID,
			&i.SealedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchResult = `-- name: UpdateMatchResult :exec
UPDATE match_results
SET sets = $2, winner_team = $3, total_games_a = $4, total_games_b = $5, game_diff = $6
WHERE match_id = $1
`

type UpdateMatchResultParams struct {
	MatchID     pgtype.UUID `json:"match_id"`
	Sets        []byte      `json:"sets"`
	WinnerTeam  string      `json:"winner_team"`
	TotalGamesA int32       `json:"total_games_a"`
	TotalGamesB int32       `json:"total_games_b"`
	GameDiff    int32       `json:"game_diff"`
}

func (q *Queries) UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error {
	_, err := q.db.Exec(ctx, updateMatchResult,
		arg.MatchID,
		arg.Sets,
		arg.WinnerTeam,
		arg.TotalGamesA,
		arg.TotalGamesB,
		arg.GameDiff,
	)
	return err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :exec
UPDATE matches
SET status = $2, sealed_by = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateMatchStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	SealedBy pgtype.Text `json:"sealed_by"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) error {
	_, err := q.db.Exec(ctx, updateMatchStatus, arg.ID, arg.Status, arg.SealedBy)
	return err
}

const updateMatchStatusCAS = `-- name: UpdateMatchStatusCAS :one
UPDATE matches
SET status = $3, sealed_by = $4, updated_at = NOW()
WHERE id = $1 AND status = $2
RETURNING id
`

type UpdateMatchStatusCASParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Status_2 string      `json:"status_2"`
	SealedBy pgtype.Text `json:"sealed_by"`
}

func (q *Queries) UpdateMatchStatusCAS(ctx context.Context, arg UpdateMatchStatusCASParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateMatchStatusCAS,
		arg.ID,
		arg.Status,
		arg.Status_2,
		arg.SealedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
