// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityFeed struct {
	ID        pgtype.UUID        `json:"id"`
	PlayerID  pgtype.UUID        `json:"player_id"`
	EventType string             `json:"event_type"`
	Content   []byte             `json:"content"`
	RegionID  pgtype.UUID        `json:"region_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AdminAuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	Action       string             `json:"action"`
	TargetUserID pgtype.UUID        `json:"target_user_id"`
	Details      []byte             `json:"details"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ConductReport struct {
	ID          pgtype.UUID        `json:"id"`
	ReporterID  pgtype.UUID        `json:"reporter_id"`
	ReportedID  pgtype.UUID        `json:"reported_id"`
	MatchID     pgtype.UUID        `json:"match_id"`
	Reason      string             `json:"reason"`
	Status      string             `json:"status"`
	ModeratorID pgtype.UUID        `json:"moderator_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DeviceToken struct {
	ID         pgtype.UUID        `json:"id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	Token      string             `json:"token"`
	Platform   string             `json:"platform"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Dispute struct {
	ID                pgtype.UUID        `json:"id"`
	MatchID           pgtype.UUID        `json:"match_id"`
	RaisedBy          pgtype.UUID        `json:"raised_by"`
	Reason            string             `json:"reason"`
	Status            string             `json:"status"`
	ResolvedBy        pgtype.UUID        `json:"resolved_by"`
	ResolutionResult  []byte             `json:"resolution_result"`
	PenalizedPlayerID pgtype.UUID        `json:"penalized_player_id"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type EloHistory struct {
	ID        pgtype.UUID        `json:"id"`
	PlayerID  pgtype.UUID        `json:"player_id"`
	MatchID   pgtype.UUID        `json:"match_id"`
	EloBefore int32              `json:"elo_before"`
	EloAfter  int32              `json:"elo_after"`
	Delta     int32              `json:"delta"`
	KFactor   int32              `json:"k_factor"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FlareRespondent struct {
	FlareID  pgtype.UUID        `json:"flare_id"`
	PlayerID pgtype.UUID        `json:"player_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Match struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Location    interface{}        `json:"location"`
	CaptainAID  pgtype.UUID        `json:"captain_a_id"`
	CaptainBID  pgtype.UUID        `json:"captain_b_id"`
	AvgElo      pgtype.Int4        `json:"avg_elo"`
	SealedBy    pgtype.Text        `json:"sealed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	RegionID    pgtype.UUID        `json:"region_id"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
}

type MatchPlayer struct {
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
	Team     string      `json:"team"`
}

type MatchResult struct {
	MatchID     pgtype.UUID        `json:"match_id"`
	Sets        []byte             `json:"sets"`
	WinnerTeam  string             `json:"winner_team"`
	TotalGamesA int32              `json:"total_games_a"`
	TotalGamesB int32              `json:"total_games_b"`
	GameDiff    int32              `json:"game_diff"`
	SubmittedBy pgtype.UUID        `json:"submitted_by"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

type MatchmakingFlare struct {
	ID          pgtype.UUID        `json:"id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	Location    interface{}        `json:"location"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	EloMin      int32              `json:"elo_min"`
	EloMax      int32              `json:"elo_max"`
	MinPlayers  int32              `json:"min_players"`
	MaxPlayers  int32              `json:"max_players"`
	Status      string             `json:"status"`
	MatchID     pgtype.UUID        `json:"match_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MatchType   string             `json:"match_type"`
	VenueID     pgtype.UUID        `json:"venue_id"`
}

type NotificationLog struct {
	ID               pgtype.UUID        `json:"id"`
	PlayerID         pgtype.UUID        `json:"player_id"`
	NotificationType string             `json:"notification_type"`
	ReferenceID      pgtype.UUID        `json:"reference_id"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
}

type OnboardingResponse struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Responses     []byte             `json:"responses"`
	CalculatedElo int32              `json:"calculated_elo"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PlayerPartnership struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	PartnerID   pgtype.UUID        `json:"partner_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Region struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Boundary    interface{}        `json:"boundary"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TrustEvent struct {
	ID          pgtype.UUID        `json:"id"`
	PlayerID    pgtype.UUID        `json:"player_id"`
	EventType   string             `json:"event_type"`
	Delta       int32              `json:"delta"`
	ReferenceID pgtype.UUID        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Name                pgtype.Text        `json:"name"`
	TrustScore          int32              `json:"trust_score"`
	LastName            pgtype.Text        `json:"last_name"`
	Location            interface{}        `json:"location"`
	RegionID            pgtype.UUID        `json:"region_id"`
	Elo                 int32              `json:"elo"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	ValidatedMatchCount int32              `json:"validated_match_count"`
	EloFrozen           bool               `json:"elo_frozen"`
	Preferences         []byte             `json:"preferences"`
	Gender              string             `json:"gender"`
}

type Venue struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	Location   interface{}        `json:"location"`
	CourtCount int32              `json:"court_count"`
	Phone      pgtype.Text        `json:"phone"`
	Hours      []byte             `json:"hours"`
	RegionID   pgtype.UUID        `json:"region_id"`
	AddedBy    pgtype.UUID        `json:"added_by"`
	Verified   bool               `json:"verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
