// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNotificationSent = `-- name: CheckNotificationSent :one
SELECT EXISTS (
    SELECT 1 FROM notification_log
    WHERE player_id = $1
      AND notification_type = $2
      AND reference_id = $3
      AND sent_at > NOW() - $4::interval
) AS sent
`

type CheckNotificationSentParams struct {
	PlayerID         pgtype.UUID     `json:"player_id"`
	NotificationType string          `json:"notification_type"`
	ReferenceID      pgtype.UUID     `json:"reference_id"`
	Column4          pgtype.Interval `json:"column_4"`
}

func (q *Queries) CheckNotificationSent(ctx context.Context, arg CheckNotificationSentParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationSent,
		arg.PlayerID,
		arg.NotificationType,
		arg.ReferenceID,
		arg.Column4,
	)
	var sent bool
	err := row.Scan(&sent)
	return sent, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :exec
INSERT INTO notification_log (player_id, notification_type, reference_id)
VALUES ($1, $2, $3)
`

type InsertNotificationLogParams struct {
	PlayerID         pgtype.UUID `json:"player_id"`
	NotificationType string      `json:"notification_type"`
	ReferenceID      pgtype.UUID `json:"reference_id"`
}

func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) error {
	_, err := q.db.Exec(ctx, insertNotificationLog, arg.PlayerID, arg.NotificationType, arg.ReferenceID)
	return err
}
