// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingResponse = `-- name: CreateOnboardingResponse :exec
INSERT INTO onboarding_responses (user_id, responses, calculated_elo)
VALUES ($1, $2, $3)
`

type CreateOnboardingResponseParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Responses     []byte      `json:"responses"`
	CalculatedElo int32       `json:"calculated_elo"`
}

func (q *Queries) CreateOnboardingResponse(ctx context.Context, arg CreateOnboardingResponseParams) error {
	_, err := q.db.Exec(ctx, createOnboardingResponse, arg.UserID, arg.Responses, arg.CalculatedElo)
	return err
}

const getOnboardingResponse = `-- name: GetOnboardingResponse :one
SELECT id, user_id, responses, calculated_elo, created_at
FROM onboarding_responses
WHERE user_id = $1
`

func (q *Queries) GetOnboardingResponse(ctx context.Context, userID pgtype.UUID) (OnboardingResponse, error) {
	row := q.db.QueryRow(ctx, getOnboardingResponse, userID)
	var i OnboardingResponse
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Responses,
		&i.CalculatedElo,
		&i.CreatedAt,
	)
	return i, err
}
