// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pair_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBestPartner = `-- name: GetBestPartner :one
WITH pair_stats AS (
    SELECT
        mp2.player_id AS partner_id,
        COUNT(*)::INT AS total_matches,
        COUNT(*) FILTER (WHERE mr.winner_team = mp1.team)::INT AS wins
    FROM match_players mp1
    JOIN match_players mp2 ON mp1.match_id = mp2.match_id
        AND mp1.team = mp2.team
        AND mp1.player_id != mp2.player_id
    JOIN matches m ON m.id = mp1.match_id AND m.status = 'sealed'
    JOIN match_results mr ON mr.match_id = mp1.match_id
    WHERE mp1.player_id = $1
    GROUP BY mp2.player_id
    HAVING COUNT(*) >= 3
)
SELECT
    ps.partner_id,
    u.name AS partner_name,
    u.elo AS partner_elo,
    ps.total_matches,
    ps.wins,
    ROUND(ps.wins::NUMERIC / ps.total_matches * 100)::INT AS win_rate_pct
FROM pair_stats ps
JOIN users u ON u.id = ps.partner_id
ORDER BY ps.wins::NUMERIC / ps.total_matches DESC, ps.total_matches DESC
LIMIT 1
`

type GetBestPartnerRow struct {
	PartnerID    pgtype.UUID `json:"partner_id"`
	PartnerName  pgtype.Text `json:"partner_name"`
	PartnerElo   int32       `json:"partner_elo"`
	TotalMatches int32       `json:"total_matches"`
	Wins         int32       `json:"wins"`
	WinRatePct   int32       `json:"win_rate_pct"`
}

func (q *Queries) GetBestPartner(ctx context.Context, playerID pgtype.UUID) (GetBestPartnerRow, error) {
	row := q.db.QueryRow(ctx, getBestPartner, playerID)
	var i GetBestPartnerRow
	err := row.Scan(
		&i.PartnerID,
		&i.PartnerName,
		&i.PartnerElo,
		&i.TotalMatches,
		&i.Wins,
		&i.WinRatePct,
	)
	return i, err
}

const getPairRecentMatches = `-- name: GetPairRecentMatches :many
SELECT
    mp1.match_id,
    CASE WHEN mr.winner_team = mp1.team THEN TRUE ELSE FALSE END AS won
FROM match_players mp1
JOIN match_players mp2 ON mp1.match_id = mp2.match_id
    AND mp1.team = mp2.team
    AND mp1.player_id != mp2.player_id
JOIN matches m ON m.id = mp1.match_id AND m.status = 'sealed'
JOIN match_results mr ON mr.match_id = mp1.match_id
WHERE mp1.player_id = $1 AND mp2.player_id = $2
ORDER BY m.created_at DESC
LIMIT 50
`

type GetPairRecentMatchesParams struct {
	PlayerA pgtype.UUID `json:"player_a"`
	PlayerB pgtype.UUID `json:"player_b"`
}

type GetPairRecentMatchesRow struct {
	MatchID pgtype.UUID `json:"match_id"`
	Won     bool        `json:"won"`
}

func (q *Queries) GetPairRecentMatches(ctx context.Context, arg GetPairRecentMatchesParams) ([]GetPairRecentMatchesRow, error) {
	rows, err := q.db.Query(ctx, getPairRecentMatches, arg.PlayerA, arg.PlayerB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPairRecentMatchesRow{}
	for rows.Next() {
		var i GetPairRecentMatchesRow
		if err := rows.Scan(&i.MatchID, &i.Won); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairStats = `-- name: GetPairStats :one
SELECT
    COUNT(*)::INT AS total_matches,
    COUNT(*) FILTER (WHERE mr.winner_team = mp1.team)::INT AS wins
FROM match_players mp1
JOIN match_players mp2 ON mp1.match_id = mp2.match_id
    AND mp1.team = mp2.team
    AND mp1.player_id != mp2.player_id
JOIN matches m ON m.id = mp1.match_id AND m.status = 'sealed'
JOIN match_results mr ON mr.match_id = mp1.match_id
WHERE mp1.player_id = $1 AND mp2.player_id = $2
`

type GetPairStatsParams struct {
	PlayerA pgtype.UUID `json:"player_a"`
	PlayerB pgtype.UUID `json:"player_b"`
}

type GetPairStatsRow struct {
	TotalMatches int32 `json:"total_matches"`
	Wins         int32 `json:"wins"`
}

func (q *Queries) GetPairStats(ctx context.Context, arg GetPairStatsParams) (GetPairStatsRow, error) {
	row := q.db.QueryRow(ctx, getPairStats, arg.PlayerA, arg.PlayerB)
	var i GetPairStatsRow
	err := row.Scan(&i.TotalMatches, &i.Wins)
	return i, err
}
