// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partnerships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePartnershipsByPlayer = `-- name: CountActivePartnershipsByPlayer :one
SELECT COUNT(*)::INT
FROM player_partnerships
WHERE (requester_id = $1 OR partner_id = $1)
  AND status = 'accepted'
`

func (q *Queries) CountActivePartnershipsByPlayer(ctx context.Context, playerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActivePartnershipsByPlayer, playerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPartnership = `-- name: CreatePartnership :one
INSERT INTO player_partnerships (requester_id, partner_id)
VALUES ($1, $2)
RETURNING id, requester_id, partner_id, status, created_at, updated_at
`

type CreatePartnershipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	PartnerID   pgtype.UUID `json:"partner_id"`
}

func (q *Queries) CreatePartnership(ctx context.Context, arg CreatePartnershipParams) (PlayerPartnership, error) {
	row := q.db.QueryRow(ctx, createPartnership, arg.RequesterID, arg.PartnerID)
	var i PlayerPartnership
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.PartnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePartnershipsByPlayer = `-- name: GetActivePartnershipsByPlayer :many
SELECT
    pp.id,
    pp.requester_id,
    pp.partner_id,
    pp.status,
    pp.created_at,
    pp.updated_at,
    u.name AS partner_name,
    u.elo AS partner_elo
FROM player_partnerships pp
JOIN users u ON u.id = CASE
    WHEN pp.requester_id = $1 THEN pp.partner_id
    ELSE pp.requester_id
END
WHERE (pp.requester_id = $1 OR pp.partner_id = $1)
  AND pp.status = 'accepted'
ORDER BY pp.created_at DESC
`

type GetActivePartnershipsByPlayerRow struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	PartnerID   pgtype.UUID        `json:"partner_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PartnerName pgtype.Text        `json:"partner_name"`
	PartnerElo  int32              `json:"partner_elo"`
}

func (q *Queries) GetActivePartnershipsByPlayer(ctx context.Context, playerID pgtype.UUID) ([]GetActivePartnershipsByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getActivePartnershipsByPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivePartnershipsByPlayerRow{}
	for rows.Next() {
		var i GetActivePartnershipsByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.PartnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartnerName,
			&i.PartnerElo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingPartnership = `-- name: GetExistingPartnership :one
SELECT id, requester_id, partner_id, status, created_at, updated_at
FROM player_partnerships
WHERE (requester_id = $1 AND partner_id = $2)
   OR (requester_id = $2 AND partner_id = $1)
LIMIT 1
`

type GetExistingPartnershipParams struct {
	PlayerA pgtype.UUID `json:"player_a"`
	PlayerB pgtype.UUID `json:"player_b"`
}

func (q *Queries) GetExistingPartnership(ctx context.Context, arg GetExistingPartnershipParams) (PlayerPartnership, error) {
	row := q.db.QueryRow(ctx, getExistingPartnership, arg.PlayerA, arg.PlayerB)
	var i PlayerPartnership
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.PartnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnershipByID = `-- name: GetPartnershipByID :one
SELECT id, requester_id, partner_id, status, created_at, updated_at
FROM player_partnerships
WHERE id = $1
`

func (q *Queries) GetPartnershipByID(ctx context.Context, id pgtype.UUID) (PlayerPartnership, error) {
	row := q.db.QueryRow(ctx, getPartnershipByID, id)
	var i PlayerPartnership
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.PartnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartnershipStatus = `-- name: UpdatePartnershipStatus :one
UPDATE player_partnerships
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, requester_id, partner_id, status, created_at, updated_at
`

type UpdatePartnershipStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePartnershipStatus(ctx context.Context, arg UpdatePartnershipStatusParams) (PlayerPartnership, error) {
	row := q.db.QueryRow(ctx, updatePartnershipStatus, arg.Status, arg.ID)
	var i PlayerPartnership
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.PartnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
