// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayerELOs = `-- name: GetPlayerELOs :many
SELECT id, elo
FROM users
WHERE id = ANY($1::uuid[])
`

type GetPlayerELOsRow struct {
	ID  pgtype.UUID `json:"id"`
	Elo int32       `json:"elo"`
}

func (q *Queries) GetPlayerELOs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetPlayerELOsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerELOs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerELOsRow{}
	for rows.Next() {
		var i GetPlayerELOsRow
		if err := rows.Scan(&i.ID, &i.Elo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerGenders = `-- name: GetPlayerGenders :many
SELECT id, gender
FROM users
WHERE id = ANY($1::uuid[])
`

type GetPlayerGendersRow struct {
	ID     pgtype.UUID `json:"id"`
	Gender string      `json:"gender"`
}

func (q *Queries) GetPlayerGenders(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetPlayerGendersRow, error) {
	rows, err := q.db.Query(ctx, getPlayerGenders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerGendersRow{}
	for rows.Next() {
		var i GetPlayerGendersRow
		if err := rows.Scan(&i.ID, &i.Gender); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerProfile = `-- name: GetPlayerProfile :one
SELECT
    id,
    email,
    name,
    last_name,
    role,
    status,
    elo,
    avatar_url,
    onboarding_completed,
    validated_match_count,
    elo_frozen,
    region_id,
    trust_score,
    gender,
    created_at,
    updated_at,
    ST_Y(location::geometry) AS latitude,
    ST_X(location::geometry) AS longitude
FROM users
WHERE id = $1
`

type GetPlayerProfileRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	Name                pgtype.Text        `json:"name"`
	LastName            pgtype.Text        `json:"last_name"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	Elo                 int32              `json:"elo"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	ValidatedMatchCount int32              `json:"validated_match_count"`
	EloFrozen           bool               `json:"elo_frozen"`
	RegionID            pgtype.UUID        `json:"region_id"`
	TrustScore          int32              `json:"trust_score"`
	Gender              string             `json:"gender"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Latitude            interface{}        `json:"latitude"`
	Longitude           interface{}        `json:"longitude"`
}

func (q *Queries) GetPlayerProfile(ctx context.Context, id pgtype.UUID) (GetPlayerProfileRow, error) {
	row := q.db.QueryRow(ctx, getPlayerProfile, id)
	var i GetPlayerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.Elo,
		&i.AvatarUrl,
		&i.OnboardingCompleted,
		&i.ValidatedMatchCount,
		&i.EloFrozen,
		&i.RegionID,
		&i.TrustScore,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getPlayerStatuses = `-- name: GetPlayerStatuses :many
SELECT id, status
FROM users
WHERE id = ANY($1::uuid[])
`

type GetPlayerStatusesRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) GetPlayerStatuses(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetPlayerStatusesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerStatuses, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerStatusesRow{}
	for rows.Next() {
		var i GetPlayerStatusesRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayersByRegion = `-- name: GetPlayersByRegion :many
SELECT
    id,
    email,
    name,
    last_name,
    role,
    status,
    elo,
    avatar_url,
    onboarding_completed,
    validated_match_count,
    elo_frozen,
    region_id,
    trust_score,
    created_at,
    updated_at,
    ST_Y(location::geometry) AS latitude,
    ST_X(location::geometry) AS longitude
FROM users
WHERE region_id = $1 AND status = 'active'
ORDER BY elo DESC
`

type GetPlayersByRegionRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	Name                pgtype.Text        `json:"name"`
	LastName            pgtype.Text        `json:"last_name"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	Elo                 int32              `json:"elo"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	ValidatedMatchCount int32              `json:"validated_match_count"`
	EloFrozen           bool               `json:"elo_frozen"`
	RegionID            pgtype.UUID        `json:"region_id"`
	TrustScore          int32              `json:"trust_score"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Latitude            interface{}        `json:"latitude"`
	Longitude           interface{}        `json:"longitude"`
}

func (q *Queries) GetPlayersByRegion(ctx context.Context, regionID pgtype.UUID) ([]GetPlayersByRegionRow, error) {
	rows, err := q.db.Query(ctx, getPlayersByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersByRegionRow{}
	for rows.Next() {
		var i GetPlayersByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.LastName,
			&i.Role,
			&i.Status,
			&i.Elo,
			&i.AvatarUrl,
			&i.OnboardingCompleted,
			&i.ValidatedMatchCount,
			&i.EloFrozen,
			&i.RegionID,
			&i.TrustScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlayersByName = `-- name: SearchPlayersByName :many
SELECT id, name, elo, avatar_url, gender
FROM users
WHERE LOWER(name) LIKE LOWER('%' || $1 || '%')
  AND status IN ('active', 'calibration')
ORDER BY elo DESC
LIMIT $2
`

type SearchPlayersByNameParams struct {
	Query       pgtype.Text `json:"query"`
	SearchLimit int32       `json:"search_limit"`
}

type SearchPlayersByNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      pgtype.Text `json:"name"`
	Elo       int32       `json:"elo"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Gender    string      `json:"gender"`
}

func (q *Queries) SearchPlayersByName(ctx context.Context, arg SearchPlayersByNameParams) ([]SearchPlayersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchPlayersByName, arg.Query, arg.SearchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersByNameRow{}
	for rows.Next() {
		var i SearchPlayersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Elo,
			&i.AvatarUrl,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOnboardingCompleted = `-- name: SetOnboardingCompleted :exec
UPDATE users
SET onboarding_completed = TRUE, elo = $2, gender = $3, updated_at = NOW()
WHERE id = $1
`

type SetOnboardingCompletedParams struct {
	ID     pgtype.UUID `json:"id"`
	Elo    int32       `json:"elo"`
	Gender string      `json:"gender"`
}

func (q *Queries) SetOnboardingCompleted(ctx context.Context, arg SetOnboardingCompletedParams) error {
	_, err := q.db.Exec(ctx, setOnboardingCompleted, arg.ID, arg.Elo, arg.Gender)
	return err
}

const updatePlayerAvatar = `-- name: UpdatePlayerAvatar :exec
UPDATE users
SET avatar_url = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePlayerAvatarParams struct {
	ID        pgtype.UUID `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdatePlayerAvatar(ctx context.Context, arg UpdatePlayerAvatarParams) error {
	_, err := q.db.Exec(ctx, updatePlayerAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updatePlayerELO = `-- name: UpdatePlayerELO :exec
UPDATE users
SET elo = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePlayerELOParams struct {
	ID  pgtype.UUID `json:"id"`
	Elo int32       `json:"elo"`
}

func (q *Queries) UpdatePlayerELO(ctx context.Context, arg UpdatePlayerELOParams) error {
	_, err := q.db.Exec(ctx, updatePlayerELO, arg.ID, arg.Elo)
	return err
}

const updatePlayerNameOnly = `-- name: UpdatePlayerNameOnly :exec
UPDATE users SET
    name = COALESCE(NULLIF($1::varchar, ''), name),
    last_name = COALESCE(NULLIF($2::varchar, ''), last_name),
    updated_at = NOW()
WHERE id = $3
`

type UpdatePlayerNameOnlyParams struct {
	Name     string      `json:"name"`
	LastName string      `json:"last_name"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePlayerNameOnly(ctx context.Context, arg UpdatePlayerNameOnlyParams) error {
	_, err := q.db.Exec(ctx, updatePlayerNameOnly, arg.Name, arg.LastName, arg.ID)
	return err
}

const updatePlayerProfile = `-- name: UpdatePlayerProfile :exec
UPDATE users
SET
    last_name = $2,
    location  = ST_MakePoint($4, $3)::geography,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePlayerProfileParams struct {
	ID            pgtype.UUID `json:"id"`
	LastName      pgtype.Text `json:"last_name"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) UpdatePlayerProfile(ctx context.Context, arg UpdatePlayerProfileParams) error {
	_, err := q.db.Exec(ctx, updatePlayerProfile,
		arg.ID,
		arg.LastName,
		arg.StMakepoint,
		arg.StMakepoint_2,
	)
	return err
}
