// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnProfile = `-- name: GetOwnProfile :one
SELECT id, name, email, elo, trust_score, validated_match_count, region_id, status, preferences, gender, created_at
FROM users
WHERE id = $1
`

type GetOwnProfileRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                pgtype.Text        `json:"name"`
	Email               string             `json:"email"`
	Elo                 int32              `json:"elo"`
	TrustScore          int32              `json:"trust_score"`
	ValidatedMatchCount int32              `json:"validated_match_count"`
	RegionID            pgtype.UUID        `json:"region_id"`
	Status              string             `json:"status"`
	Preferences         []byte             `json:"preferences"`
	Gender              string             `json:"gender"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOwnProfile(ctx context.Context, id pgtype.UUID) (GetOwnProfileRow, error) {
	row := q.db.QueryRow(ctx, getOwnProfile, id)
	var i GetOwnProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Elo,
		&i.TrustScore,
		&i.ValidatedMatchCount,
		&i.RegionID,
		&i.Status,
		&i.Preferences,
		&i.Gender,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT id, name, elo, trust_score, validated_match_count, region_id, status, gender
FROM users
WHERE id = $1
`

type GetPublicProfileRow struct {
	ID                  pgtype.UUID `json:"id"`
	Name                pgtype.Text `json:"name"`
	Elo                 int32       `json:"elo"`
	TrustScore          int32       `json:"trust_score"`
	ValidatedMatchCount int32       `json:"validated_match_count"`
	RegionID            pgtype.UUID `json:"region_id"`
	Status              string      `json:"status"`
	Gender              string      `json:"gender"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, id pgtype.UUID) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, id)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Elo,
		&i.TrustScore,
		&i.ValidatedMatchCount,
		&i.RegionID,
		&i.Status,
		&i.Gender,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :exec
UPDATE users
SET preferences = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePreferencesParams struct {
	ID          pgtype.UUID `json:"id"`
	Preferences []byte      `json:"preferences"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) error {
	_, err := q.db.Exec(ctx, updatePreferences, arg.ID, arg.Preferences)
	return err
}
