// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: radar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRadarAlerts = `-- name: GetRadarAlerts :many
SELECT
    m.id,
    m.captain_a_id                                                                          AS captain_id,
    ca.name                                                                                  AS captain_name,
    ST_Y(m.location::geometry)::float8                                                       AS lat,
    ST_X(m.location::geometry)::float8                                                       AS lng,
    ST_Distance(m.location, ST_MakePoint($2, $1)::geography)::float8                        AS distance_meters,
    m.avg_elo,
    m.scheduled_at,
    COUNT(mp.player_id)::int4                                                                AS joined_count
FROM matches m
JOIN users ca ON ca.id = m.captain_a_id
JOIN users viewer ON viewer.id = $3
LEFT JOIN match_players mp ON mp.match_id = m.id
WHERE m.status = 'pending_result'
  AND m.scheduled_at BETWEEN NOW() AND NOW() + INTERVAL '1 hour'
  AND m.location IS NOT NULL
  AND ST_DWithin(m.location, ST_MakePoint($2, $1)::geography, 5000)
  AND (ca.trust_score >= 70 OR viewer.trust_score < 70)
GROUP BY m.id, ca.name, viewer.trust_score
ORDER BY m.scheduled_at ASC
`

type GetRadarAlertsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	ID            pgtype.UUID `json:"id"`
}

type GetRadarAlertsRow struct {
	ID             pgtype.UUID        `json:"id"`
	CaptainID      pgtype.UUID        `json:"captain_id"`
	CaptainName    pgtype.Text        `json:"captain_name"`
	Lat            float64            `json:"lat"`
	Lng            float64            `json:"lng"`
	DistanceMeters float64            `json:"distance_meters"`
	AvgElo         pgtype.Int4        `json:"avg_elo"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	JoinedCount    int32              `json:"joined_count"`
}

// Radar alerts: matches within 5km and next 1 hour, trust filter, no ELO filter
func (q *Queries) GetRadarAlerts(ctx context.Context, arg GetRadarAlertsParams) ([]GetRadarAlertsRow, error) {
	rows, err := q.db.Query(ctx, getRadarAlerts, arg.StMakepoint, arg.StMakepoint_2, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRadarAlertsRow{}
	for rows.Next() {
		var i GetRadarAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.CaptainID,
			&i.CaptainName,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
			&i.AvgElo,
			&i.ScheduledAt,
			&i.JoinedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRadarMatches = `-- name: GetRadarMatches :many
SELECT
    m.id,
    m.captain_a_id                                                                          AS captain_id,
    ca.name                                                                                  AS captain_name,
    ST_Y(m.location::geometry)::float8                                                       AS lat,
    ST_X(m.location::geometry)::float8                                                       AS lng,
    ST_Distance(m.location, ST_MakePoint($2, $1)::geography)::float8                        AS distance_meters,
    m.avg_elo,
    m.scheduled_at,
    COUNT(mp.player_id)::int4                                                                AS joined_count
FROM matches m
JOIN users ca ON ca.id = m.captain_a_id
JOIN users viewer ON viewer.id = $8
LEFT JOIN match_players mp ON mp.match_id = m.id
WHERE m.status = 'pending_result'
  AND m.scheduled_at BETWEEN NOW() AND NOW() + INTERVAL '48 hours'
  AND m.location IS NOT NULL
  AND ST_DWithin(m.location, ST_MakePoint($2, $1)::geography, $3)
  AND m.avg_elo BETWEEN $4 AND $5
  AND (ca.trust_score >= 70 OR viewer.trust_score < 70)
  AND (
      $6::timestamptz IS NULL
      OR (m.scheduled_at, m.id) > ($6::timestamptz, $7::uuid)
  )
GROUP BY m.id, ca.name, viewer.trust_score
ORDER BY m.scheduled_at ASC, m.id ASC
LIMIT $9
`

type GetRadarMatchesParams struct {
	StMakepoint   interface{}        `json:"st_makepoint"`
	StMakepoint_2 interface{}        `json:"st_makepoint_2"`
	StDwithin     interface{}        `json:"st_dwithin"`
	AvgElo        pgtype.Int4        `json:"avg_elo"`
	AvgElo_2      pgtype.Int4        `json:"avg_elo_2"`
	Column6       pgtype.Timestamptz `json:"column_6"`
	Column7       pgtype.UUID        `json:"column_7"`
	ID            pgtype.UUID        `json:"id"`
	Limit         int32              `json:"limit"`
}

type GetRadarMatchesRow struct {
	ID             pgtype.UUID        `json:"id"`
	CaptainID      pgtype.UUID        `json:"captain_id"`
	CaptainName    pgtype.Text        `json:"captain_name"`
	Lat            float64            `json:"lat"`
	Lng            float64            `json:"lng"`
	DistanceMeters float64            `json:"distance_meters"`
	AvgElo         pgtype.Int4        `json:"avg_elo"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	JoinedCount    int32              `json:"joined_count"`
}

// Radar: open matches within radius + ELO range + trust filter
// Cursor-based pagination on (scheduled_at, id)
func (q *Queries) GetRadarMatches(ctx context.Context, arg GetRadarMatchesParams) ([]GetRadarMatchesRow, error) {
	rows, err := q.db.Query(ctx, getRadarMatches,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.StDwithin,
		arg.AvgElo,
		arg.AvgElo_2,
		arg.Column6,
		arg.Column7,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRadarMatchesRow{}
	for rows.Next() {
		var i GetRadarMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaptainID,
			&i.CaptainName,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
			&i.AvgElo,
			&i.ScheduledAt,
			&i.JoinedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
