// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rankings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegion = `-- name: CreateRegion :one
INSERT INTO regions (name, boundary)
VALUES ($1, ST_GeomFromText($2, 4326))
RETURNING id, name
`

type CreateRegionParams struct {
	Name           string      `json:"name"`
	StGeomfromtext interface{} `json:"st_geomfromtext"`
}

type CreateRegionRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (CreateRegionRow, error) {
	row := q.db.QueryRow(ctx, createRegion, arg.Name, arg.StGeomfromtext)
	var i CreateRegionRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAllRegions = `-- name: GetAllRegions :many
SELECT id, name FROM regions ORDER BY name
`

type GetAllRegionsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetAllRegions(ctx context.Context) ([]GetAllRegionsRow, error) {
	rows, err := q.db.Query(ctx, getAllRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllRegionsRow{}
	for rows.Next() {
		var i GetAllRegionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRank = `-- name: GetPlayerRank :one
SELECT r.rank
FROM (
    SELECT
        u.id AS uid,
        RANK() OVER (ORDER BY u.elo DESC) AS rank
    FROM users u
    WHERE u.region_id = (SELECT region_id FROM users WHERE users.id = $1)
      AND u.status = 'active'
) r
WHERE r.uid = $1
`

func (q *Queries) GetPlayerRank(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPlayerRank, id)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const getPlayerRankByGender = `-- name: GetPlayerRankByGender :one
SELECT r.rank
FROM (
    SELECT
        u.id AS uid,
        RANK() OVER (ORDER BY u.elo DESC) AS rank
    FROM users u
    WHERE u.region_id = (SELECT region_id FROM users WHERE users.id = $1)
      AND u.status = 'active'
      AND u.gender = $2
) r
WHERE r.uid = $1
`

type GetPlayerRankByGenderParams struct {
	ID     pgtype.UUID `json:"id"`
	Gender string      `json:"gender"`
}

func (q *Queries) GetPlayerRankByGender(ctx context.Context, arg GetPlayerRankByGenderParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPlayerRankByGender, arg.ID, arg.Gender)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const getRankingByRegion = `-- name: GetRankingByRegion :many
SELECT
    u.id,
    u.name,
    u.elo,
    u.validated_match_count,
    RANK() OVER (ORDER BY u.elo DESC) AS rank
FROM users u
WHERE u.region_id = $1
  AND u.status = 'active'
ORDER BY u.elo DESC
LIMIT $2 OFFSET $3
`

type GetRankingByRegionParams struct {
	RegionID pgtype.UUID `json:"region_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetRankingByRegionRow struct {
	ID                  pgtype.UUID `json:"id"`
	Name                pgtype.Text `json:"name"`
	Elo                 int32       `json:"elo"`
	ValidatedMatchCount int32       `json:"validated_match_count"`
	Rank                int64       `json:"rank"`
}

func (q *Queries) GetRankingByRegion(ctx context.Context, arg GetRankingByRegionParams) ([]GetRankingByRegionRow, error) {
	rows, err := q.db.Query(ctx, getRankingByRegion, arg.RegionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRankingByRegionRow{}
	for rows.Next() {
		var i GetRankingByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Elo,
			&i.ValidatedMatchCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRankingByRegionAndGender = `-- name: GetRankingByRegionAndGender :many
SELECT
    u.id,
    u.name,
    u.elo,
    u.validated_match_count,
    u.gender,
    RANK() OVER (ORDER BY u.elo DESC) AS rank
FROM users u
WHERE u.region_id = $1
  AND u.status = 'active'
  AND u.gender = $4
ORDER BY u.elo DESC
LIMIT $2 OFFSET $3
`

type GetRankingByRegionAndGenderParams struct {
	RegionID pgtype.UUID `json:"region_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Gender   string      `json:"gender"`
}

type GetRankingByRegionAndGenderRow struct {
	ID                  pgtype.UUID `json:"id"`
	Name                pgtype.Text `json:"name"`
	Elo                 int32       `json:"elo"`
	ValidatedMatchCount int32       `json:"validated_match_count"`
	Gender              string      `json:"gender"`
	Rank                int64       `json:"rank"`
}

func (q *Queries) GetRankingByRegionAndGender(ctx context.Context, arg GetRankingByRegionAndGenderParams) ([]GetRankingByRegionAndGenderRow, error) {
	rows, err := q.db.Query(ctx, getRankingByRegionAndGender,
		arg.RegionID,
		arg.Limit,
		arg.Offset,
		arg.Gender,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRankingByRegionAndGenderRow{}
	for rows.Next() {
		var i GetRankingByRegionAndGenderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Elo,
			&i.ValidatedMatchCount,
			&i.Gender,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegionNameByID = `-- name: GetRegionNameByID :one
SELECT name FROM regions WHERE id = $1
`

func (q *Queries) GetRegionNameByID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRegionNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
