// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trust_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentDisputes = `-- name: CountRecentDisputes :one
SELECT COUNT(*)::integer AS count
FROM trust_events
WHERE player_id = $1
  AND event_type IN ('dispute', 'systematic_dispute')
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) CountRecentDisputes(ctx context.Context, playerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentDisputes, playerID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getMonthlyRecoverySum = `-- name: GetMonthlyRecoverySum :one
SELECT COALESCE(SUM(delta), 0)::integer AS total
FROM trust_events
WHERE player_id = $1
  AND event_type = 'match_completed'
  AND created_at >= date_trunc('month', NOW())
`

func (q *Queries) GetMonthlyRecoverySum(ctx context.Context, playerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMonthlyRecoverySum, playerID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getTrustEvents = `-- name: GetTrustEvents :many
SELECT id, player_id, event_type, delta, reference_id, created_at FROM trust_events WHERE player_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetTrustEventsParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetTrustEvents(ctx context.Context, arg GetTrustEventsParams) ([]TrustEvent, error) {
	rows, err := q.db.Query(ctx, getTrustEvents, arg.PlayerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustEvent{}
	for rows.Next() {
		var i TrustEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.EventType,
			&i.Delta,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrustEvent = `-- name: InsertTrustEvent :one
INSERT INTO trust_events (player_id, event_type, delta, reference_id)
VALUES ($1, $2, $3, $4)
RETURNING id, player_id, event_type, delta, reference_id, created_at
`

type InsertTrustEventParams struct {
	PlayerID    pgtype.UUID `json:"player_id"`
	EventType   string      `json:"event_type"`
	Delta       int32       `json:"delta"`
	ReferenceID pgtype.UUID `json:"reference_id"`
}

func (q *Queries) InsertTrustEvent(ctx context.Context, arg InsertTrustEventParams) (TrustEvent, error) {
	row := q.db.QueryRow(ctx, insertTrustEvent,
		arg.PlayerID,
		arg.EventType,
		arg.Delta,
		arg.ReferenceID,
	)
	var i TrustEvent
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.EventType,
		&i.Delta,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}
