// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_ranking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const freezePlayerELO = `-- name: FreezePlayerELO :exec
UPDATE users SET elo_frozen = true, updated_at = NOW() WHERE id = $1
`

func (q *Queries) FreezePlayerELO(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, freezePlayerELO, id)
	return err
}

const getPlayerELO = `-- name: GetPlayerELO :one
SELECT id, elo, validated_match_count, elo_frozen FROM users WHERE id = $1
`

type GetPlayerELORow struct {
	ID                  pgtype.UUID `json:"id"`
	Elo                 int32       `json:"elo"`
	ValidatedMatchCount int32       `json:"validated_match_count"`
	EloFrozen           bool        `json:"elo_frozen"`
}

func (q *Queries) GetPlayerELO(ctx context.Context, id pgtype.UUID) (GetPlayerELORow, error) {
	row := q.db.QueryRow(ctx, getPlayerELO, id)
	var i GetPlayerELORow
	err := row.Scan(
		&i.ID,
		&i.Elo,
		&i.ValidatedMatchCount,
		&i.EloFrozen,
	)
	return i, err
}

const getPlayerTrustScore = `-- name: GetPlayerTrustScore :one
SELECT id, trust_score FROM users WHERE id = $1
`

type GetPlayerTrustScoreRow struct {
	ID         pgtype.UUID `json:"id"`
	TrustScore int32       `json:"trust_score"`
}

func (q *Queries) GetPlayerTrustScore(ctx context.Context, id pgtype.UUID) (GetPlayerTrustScoreRow, error) {
	row := q.db.QueryRow(ctx, getPlayerTrustScore, id)
	var i GetPlayerTrustScoreRow
	err := row.Scan(&i.ID, &i.TrustScore)
	return i, err
}

const unfreezePlayerELO = `-- name: UnfreezePlayerELO :exec
UPDATE users SET elo_frozen = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UnfreezePlayerELO(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unfreezePlayerELO, id)
	return err
}

const updatePlayerELOAndCount = `-- name: UpdatePlayerELOAndCount :exec
UPDATE users SET elo = $2, validated_match_count = validated_match_count + 1, updated_at = NOW() WHERE id = $1
`

type UpdatePlayerELOAndCountParams struct {
	ID  pgtype.UUID `json:"id"`
	Elo int32       `json:"elo"`
}

func (q *Queries) UpdatePlayerELOAndCount(ctx context.Context, arg UpdatePlayerELOAndCountParams) error {
	_, err := q.db.Exec(ctx, updatePlayerELOAndCount, arg.ID, arg.Elo)
	return err
}

const updateTrustScore = `-- name: UpdateTrustScore :exec
UPDATE users SET trust_score = $2, updated_at = NOW() WHERE id = $1
`

type UpdateTrustScoreParams struct {
	ID         pgtype.UUID `json:"id"`
	TrustScore int32       `json:"trust_score"`
}

func (q *Queries) UpdateTrustScore(ctx context.Context, arg UpdateTrustScoreParams) error {
	_, err := q.db.Exec(ctx, updateTrustScore, arg.ID, arg.TrustScore)
	return err
}
