// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, last_name, role, status, trust_score)
VALUES ($1, $2, $3, $4, 'player', 'calibration', 80)
RETURNING id, email, password_hash, role, status, created_at, updated_at, name, trust_score, last_name, location, region_id, elo, avatar_url, onboarding_completed, validated_match_count, elo_frozen, preferences, gender
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	LastName     pgtype.Text `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name, arg.LastName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TrustScore,
		&i.LastName,
		&i.Location,
		&i.RegionID,
		&i.Elo,
		&i.AvatarUrl,
		&i.OnboardingCompleted,
		&i.ValidatedMatchCount,
		&i.EloFrozen,
		&i.Preferences,
		&i.Gender,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, status, created_at, updated_at, name, trust_score, last_name, location, region_id, elo, avatar_url, onboarding_completed, validated_match_count, elo_frozen, preferences, gender FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TrustScore,
		&i.LastName,
		&i.Location,
		&i.RegionID,
		&i.Elo,
		&i.AvatarUrl,
		&i.OnboardingCompleted,
		&i.ValidatedMatchCount,
		&i.EloFrozen,
		&i.Preferences,
		&i.Gender,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, status, created_at, updated_at, name, trust_score, last_name, location, region_id, elo, avatar_url, onboarding_completed, validated_match_count, elo_frozen, preferences, gender FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.TrustScore,
		&i.LastName,
		&i.Location,
		&i.RegionID,
		&i.Elo,
		&i.AvatarUrl,
		&i.OnboardingCompleted,
		&i.ValidatedMatchCount,
		&i.EloFrozen,
		&i.Preferences,
		&i.Gender,
	)
	return i, err
}

const updatePlayerStatus = `-- name: UpdatePlayerStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePlayerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePlayerStatus(ctx context.Context, arg UpdatePlayerStatusParams) error {
	_, err := q.db.Exec(ctx, updatePlayerStatus, arg.ID, arg.Status)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
