// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, location, court_count, phone, hours, region_id, added_by)
VALUES (
    $1,
    $2,
    ST_MakePoint($3, $4)::geography,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, name, address, court_count, phone, hours, region_id, added_by, verified,
    ST_Y(location::geometry) AS lat,
    ST_X(location::geometry) AS lng,
    created_at, updated_at
`

type CreateVenueParams struct {
	Name       string      `json:"name"`
	Address    string      `json:"address"`
	Lng        interface{} `json:"lng"`
	Lat        interface{} `json:"lat"`
	CourtCount int32       `json:"court_count"`
	Phone      pgtype.Text `json:"phone"`
	Hours      []byte      `json:"hours"`
	RegionID   pgtype.UUID `json:"region_id"`
	AddedBy    pgtype.UUID `json:"added_by"`
}

type CreateVenueRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	CourtCount int32              `json:"court_count"`
	Phone      pgtype.Text        `json:"phone"`
	Hours      []byte             `json:"hours"`
	RegionID   pgtype.UUID        `json:"region_id"`
	AddedBy    pgtype.UUID        `json:"added_by"`
	Verified   bool               `json:"verified"`
	Lat        interface{}        `json:"lat"`
	Lng        interface{}        `json:"lng"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (CreateVenueRow, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.Lng,
		arg.Lat,
		arg.CourtCount,
		arg.Phone,
		arg.Hours,
		arg.RegionID,
		arg.AddedBy,
	)
	var i CreateVenueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CourtCount,
		&i.Phone,
		&i.Hours,
		&i.RegionID,
		&i.AddedBy,
		&i.Verified,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT
    id, name, address, court_count, phone, hours, region_id, added_by, verified,
    ST_Y(location::geometry) AS lat,
    ST_X(location::geometry) AS lng,
    created_at, updated_at
FROM venues
WHERE id = $1
`

type GetVenueByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	CourtCount int32              `json:"court_count"`
	Phone      pgtype.Text        `json:"phone"`
	Hours      []byte             `json:"hours"`
	RegionID   pgtype.UUID        `json:"region_id"`
	AddedBy    pgtype.UUID        `json:"added_by"`
	Verified   bool               `json:"verified"`
	Lat        interface{}        `json:"lat"`
	Lng        interface{}        `json:"lng"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVenueByID(ctx context.Context, id pgtype.UUID) (GetVenueByIDRow, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i GetVenueByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CourtCount,
		&i.Phone,
		&i.Hours,
		&i.RegionID,
		&i.AddedBy,
		&i.Verified,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenuesNearby = `-- name: GetVenuesNearby :many
SELECT
    id, name, address, court_count, phone, hours, region_id, added_by, verified,
    ST_Y(location::geometry) AS lat,
    ST_X(location::geometry) AS lng,
    ST_Distance(location, ST_MakePoint($1, $2)::geography) AS distance_meters,
    created_at, updated_at
FROM venues
WHERE ST_DWithin(location, ST_MakePoint($1, $2)::geography, $3)
ORDER BY distance_meters ASC
LIMIT $5 OFFSET $4
`

type GetVenuesNearbyParams struct {
	Lng          interface{} `json:"lng"`
	Lat          interface{} `json:"lat"`
	RadiusMeters interface{} `json:"radius_meters"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

type GetVenuesNearbyRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Address        string             `json:"address"`
	CourtCount     int32              `json:"court_count"`
	Phone          pgtype.Text        `json:"phone"`
	Hours          []byte             `json:"hours"`
	RegionID       pgtype.UUID        `json:"region_id"`
	AddedBy        pgtype.UUID        `json:"added_by"`
	Verified       bool               `json:"verified"`
	Lat            interface{}        `json:"lat"`
	Lng            interface{}        `json:"lng"`
	DistanceMeters interface{}        `json:"distance_meters"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVenuesNearby(ctx context.Context, arg GetVenuesNearbyParams) ([]GetVenuesNearbyRow, error) {
	rows, err := q.db.Query(ctx, getVenuesNearby,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVenuesNearbyRow{}
	for rows.Next() {
		var i GetVenuesNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CourtCount,
			&i.Phone,
			&i.Hours,
			&i.RegionID,
			&i.AddedBy,
			&i.Verified,
			&i.Lat,
			&i.Lng,
			&i.DistanceMeters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET
    name = COALESCE(NULLIF($1::varchar, ''), name),
    address = COALESCE(NULLIF($2::text, ''), address),
    court_count = COALESCE(NULLIF($3::int, 0), court_count),
    phone = COALESCE(NULLIF($4::varchar, ''), phone),
    hours = COALESCE($5::jsonb, hours),
    verified = $6,
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, address, court_count, phone, hours, region_id, added_by, verified,
    ST_Y(location::geometry) AS lat,
    ST_X(location::geometry) AS lng,
    created_at, updated_at
`

type UpdateVenueParams struct {
	Name       string      `json:"name"`
	Address    string      `json:"address"`
	CourtCount int32       `json:"court_count"`
	Phone      string      `json:"phone"`
	Hours      []byte      `json:"hours"`
	Verified   bool        `json:"verified"`
	ID         pgtype.UUID `json:"id"`
}

type UpdateVenueRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Address    string             `json:"address"`
	CourtCount int32              `json:"court_count"`
	Phone      pgtype.Text        `json:"phone"`
	Hours      []byte             `json:"hours"`
	RegionID   pgtype.UUID        `json:"region_id"`
	AddedBy    pgtype.UUID        `json:"added_by"`
	Verified   bool               `json:"verified"`
	Lat        interface{}        `json:"lat"`
	Lng        interface{}        `json:"lng"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (UpdateVenueRow, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.Name,
		arg.Address,
		arg.CourtCount,
		arg.Phone,
		arg.Hours,
		arg.Verified,
		arg.ID,
	)
	var i UpdateVenueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CourtCount,
		&i.Phone,
		&i.Hours,
		&i.RegionID,
		&i.AddedBy,
		&i.Verified,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
